#!/usr/bin/env bash

set -e

dockerfile_id="$1"
dockerfile="./Dockerfiles/Dockerfile.$dockerfile_id"

if [ ! -f "$dockerfile" ]; then
    echo "error: file \"$dockerfile\" not found" >&2
    exit 1
fi

podman build --tag "$dockerfile_id" --file "$dockerfile"
toolbox create --image "$dockerfile_id" "$dockerfile_id"
